services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_SECRET_KEY: minio12345
      MINIO_ROOT_PASSWORD: minio12345
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    command: node dist/main.js
    environment:
      PORT: 5050
      NODE_ENV: production
      APP_URL: http://localhost:8080
      CLIENT_ORIGIN: http://localhost:8080
      MONGODB_URI: mongodb://mongo:27017/placecell
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-change-me-to-a-long-random-string-prod}
      ADMIN_SIGNUP_CODE: ${ADMIN_SIGNUP_CODE:-change-me-too-prod}
      STORAGE_BACKEND: s3
      S3_BUCKET: placecell-resumes
      S3_REGION: us-east-1
      S3_ACCESS_KEY_ID: minio
      S3_SECRET_ACCESS_KEY: minio12345
      S3_ENDPOINT: http://minio:9000
      LLM_PROVIDER: ollama
    depends_on:
      - mongo
      - redis
      - minio
    expose:
      - "5050"
    deploy:
      replicas: 1

  api-b:
    build:
      context: .
      dockerfile: server/Dockerfile
    command: node dist/main.js
    environment:
      PORT: 5050
      NODE_ENV: production
      APP_URL: http://localhost:8080
      CLIENT_ORIGIN: http://localhost:8080
      MONGODB_URI: mongodb://mongo:27017/placecell
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-change-me-to-a-long-random-string-prod}
      ADMIN_SIGNUP_CODE: ${ADMIN_SIGNUP_CODE:-change-me-too-prod}
      STORAGE_BACKEND: s3
      S3_BUCKET: placecell-resumes
      S3_REGION: us-east-1
      S3_ACCESS_KEY_ID: minio
      S3_SECRET_ACCESS_KEY: minio12345
      S3_ENDPOINT: http://minio:9000
      LLM_PROVIDER: ollama
    depends_on:
      - mongo
      - redis
      - minio
    expose:
      - "5050"

  worker:
    build:
      context: .
      dockerfile: server/Dockerfile
    command: node dist/worker.js
    environment:
      NODE_ENV: production
      APP_URL: http://localhost:8080
      MONGODB_URI: mongodb://mongo:27017/placecell
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-change-me-to-a-long-random-string-prod}
      ADMIN_SIGNUP_CODE: ${ADMIN_SIGNUP_CODE:-change-me-too-prod}
      STORAGE_BACKEND: s3
      S3_BUCKET: placecell-resumes
      S3_REGION: us-east-1
      S3_ACCESS_KEY_ID: minio
      S3_SECRET_ACCESS_KEY: minio12345
      S3_ENDPOINT: http://minio:9000
      LLM_PROVIDER: ollama
    depends_on:
      - mongo
      - redis
      - minio

  proxy:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./docs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - api-b

volumes:
  mongo_data:
  minio_data:
