upstream placecell_api {
  server api:5050;
  server api-b:5050;
}

server {
  listen 80;

  location /v1/ {
    proxy_pass http://placecell_api;
    proxy_set_header Host $host;
    proxy_set_header X-Request-Id $request_id;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /health {
    proxy_pass http://placecell_api;
  }

  location /ready {
    proxy_pass http://placecell_api;
  }
}
